<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conceitos PHP</title>
</head>
<body>
    <h1>Meus Aprendizados sobre PHP</h1>
    <h2>Operadores</h2>
    <ul>
        <li>Aritméticos: <a href="aritimeticos.php">Ver Mais</a></li>
        <li>Atribuição: <a href="atribuicao.php">Ver Mais</a></li>
        <li>Comparação: <a href="comparacao.php">Ver Mais</a></li>
    </ul>
    <h2>Operadores Condicionais</h2>
    <ul>
        <li>Estrutura de IF Else: <a href="if.php">Ver Mais</a></li>
    </ul>
    <h2>Arrays</h2>
    <ul>
        <li>Array: <a href="array.php">Ver Mais</a></li>
        <li>Array Funções: <a href="array_funoes.php">Ver Mais</a></li>
        <li>Array Atividade: <a href="atividade_array.php">Ver Mais</a></li>
    </ul>
    <h2>For e While</h2>
    <ul>
        <li>Laço de Repetição: <a href="laço_de_repetiçao.php">Ver Mais</a></li>
        <li>While: <a href="while.php">Ver Mais</a></li>
    </ul>
</body>
</html>